version: '3'
services:
  sigsci-agent-sidecar:
    build: 
     context: ../sigsci-sidecar-alpine
     dockerfile: Dockerfile
    environment:
     - SIGSCI_ACCESSKEYID
     - SIGSCI_SECRETACCESSKEY
    volumes:
      - "varrun:/var/run/"
  sigsci-juiceshop:
    build:
      context: ./juice-shop
      dockerfile: Dockerfile
    ports:
     - "8888:3000"
    volumes:
      - "varrun:/var/run/"

volumes:
  varrun:
